apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata: 
  name: my-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      external:
        type: route
      plain: {}
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}